### ISSUE TITLE
Set up experiment-> added variables (VOL)

### ISSUE THREAD

**Issue by NessaNoctiluca** [cytoflow/cytoflow#274] opened 2020-08-28 09:14 UTC
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
  - What were you trying to do?  When setting up the experiment: Add a column with the sample volume (which is in the meta data)
  - What happened? First it appears in the list, but after importing, when I look at the list again (in set up experiment) it disappeared.
  - What did you expect to happen? To stay in the list so I can later on have it in the output list. Although I haven't found a way to actually get that information into the output
  
**Don't forget to attach the log file to this bug report!** 
[SetUpExperiment_noVOLascolumn_200828.log](https://github.com/bpteague/cytoflow/files/5141169/SetUpExperiment_noVOLascolumn_200828.log)

**Comment by bpteague** [comment] 2021-07-28 20:39
Let me make sure I understand what you were trying to do:
- You added the tubes you wanted
- You clicked "Add a variable"
- You left the type set to "FCS Metadata" and changed the "Name" to the metadata you wanted
- You clicked "OK"

This is actually intended behavior (though poorly documented -- oops!) -- sometimes seeing the metadata is useful in setting up the experiment, but you don't actually want it included in the final table. For example, if you use an autosampler on a BD instrument, FACSDiva will record the row and column from the autosampler in FCS metadata. You want to know that to fill out the table correctly, but you also don't want "ROW" and "COLUMN" as experimental conditions.

The trick is to add one last step. Once you've got the metadata as a column in the "Tubes" table, *change the type to something else* -- usually either Number or Category. `cytoflow` will then include that column (with that data type) as an experimental variable.

I'm going to go add that procedure to the documentation; I'll close this bug when I do. If I have misinterpreted what you were trying to do, please let me know!

**Comment by bpteague** [comment] 2021-07-28 21:13
....and I've added your question to the FAQ in the documentation. Thanks again for the bug report (:

**Closed by bpteague** 2021-07-28 21:13 UTC
